/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IssuerRouteImport } from './routes/issuer'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfferingsIndexRouteImport } from './routes/offerings.index'
import { Route as OfferingsAddressRouteImport } from './routes/offerings_.$address'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuerRoute = IssuerRouteImport.update({
  id: '/issuer',
  path: '/issuer',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsIndexRoute = OfferingsIndexRouteImport.update({
  id: '/offerings/',
  path: '/offerings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsAddressRoute = OfferingsAddressRouteImport.update({
  id: '/offerings_/$address',
  path: '/offerings/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investor': typeof InvestorRoute
  '/issuer': typeof IssuerRoute
  '/onboarding': typeof OnboardingRoute
  '/offerings/$address': typeof OfferingsAddressRoute
  '/offerings/': typeof OfferingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investor': typeof InvestorRoute
  '/issuer': typeof IssuerRoute
  '/onboarding': typeof OnboardingRoute
  '/offerings/$address': typeof OfferingsAddressRoute
  '/offerings': typeof OfferingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investor': typeof InvestorRoute
  '/issuer': typeof IssuerRoute
  '/onboarding': typeof OnboardingRoute
  '/offerings_/$address': typeof OfferingsAddressRoute
  '/offerings/': typeof OfferingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investor'
    | '/issuer'
    | '/onboarding'
    | '/offerings/$address'
    | '/offerings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investor'
    | '/issuer'
    | '/onboarding'
    | '/offerings/$address'
    | '/offerings'
  id:
    | '__root__'
    | '/'
    | '/investor'
    | '/issuer'
    | '/onboarding'
    | '/offerings_/$address'
    | '/offerings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestorRoute: typeof InvestorRoute
  IssuerRoute: typeof IssuerRoute
  OnboardingRoute: typeof OnboardingRoute
  OfferingsAddressRoute: typeof OfferingsAddressRoute
  OfferingsIndexRoute: typeof OfferingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuer': {
      id: '/issuer'
      path: '/issuer'
      fullPath: '/issuer'
      preLoaderRoute: typeof IssuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings/': {
      id: '/offerings/'
      path: '/offerings'
      fullPath: '/offerings/'
      preLoaderRoute: typeof OfferingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings_/$address': {
      id: '/offerings_/$address'
      path: '/offerings/$address'
      fullPath: '/offerings/$address'
      preLoaderRoute: typeof OfferingsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestorRoute: InvestorRoute,
  IssuerRoute: IssuerRoute,
  OnboardingRoute: OnboardingRoute,
  OfferingsAddressRoute: OfferingsAddressRoute,
  OfferingsIndexRoute: OfferingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
